test: ci

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -2,23 +2,17 @@
 name: Publish
 on:
   push:
-    branches:
-      - master
+    tags:
+      - 'v*'
 
 jobs:
-  tag_branch:
-    name: Publish version tag
-    runs-on: ubuntu-latest
-    timeout-minutes: 5
+  gen_doc:
+    name: Generate docs and changelog
+    runs-on: macos-latest
+    timeout-minutes: 30
     steps:
       - name: Checkout changes
         uses: actions/checkout@v2
-
-      - name: Create Semantic Release tag
-        uses: cycjimmy/semantic-release-action@v2
-        id: semantic
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Retrieve changelog from Github PR body
         run:
@@ -30,193 +24,168 @@ jobs:
               echo "[Error] empty changelog"; exit 1;
           fi
 
-          cat /tmp/changelog | sed '/<!--/,/-->/d' > /tmp/changelog_nc;
-          echo "##[set-env name=CHANGELOG;]$(cat /tmp/changelog_nc)"
+          cat /tmp/changelog | sed '/<!--/,/-->/d' >
 
-      - name: Create Release
-        uses: actions/create-release@latest
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{ steps.semantic.outputs.new_release_version }}
-          release_name:
-            Release ${{ steps.semantic.outputs.new_release_version }}
-          body: ${{ env.CHANGELOG }}
+      # - name: Install Go
+      #   uses: actions/setup-go@v1
+      #   with:
+      #     go-version: 1.14
 
-  gen_doc:
-    name: Publish Bridge and Core
-    runs-on: macos-latest
-    timeout-minutes: 30
-    steps:
-      - name: Checkout changes
-        uses: actions/checkout@v2
+      # - name: Set GOPATH in env
+      #   run: |
+      #     echo "##[set-env name=GOPATH;]$(go env GOPATH)"
+      #     echo "##[add-path]$(go env GOPATH)/bin"
+      #     mkdir -p $(go env GOPATH)/src/github.com/ipfs-shipyard
+      #     ln -s $PWD $(go env GOPATH)/src/github.com/ipfs-shipyard/gomobile-ipfs
+      #   shell: bash
 
-      - name: Install Go
-        uses: actions/setup-go@v1
-        with:
-          go-version: 1.14
+      # - name: Restore Go mod cache
+      #   id: cache
+      #   uses: actions/cache@v1
+      #   with:
+      #     path: ~/go/pkg/mod
+      #     key: ${{ runner.os }}-go-${{ hashFiles('go/go.sum') }}
 
-      - name: Set GOPATH in env
-        run: |
-          echo "##[set-env name=GOPATH;]$(go env GOPATH)"
-          echo "##[add-path]$(go env GOPATH)/bin"
-          mkdir -p $(go env GOPATH)/src/github.com/ipfs-shipyard
-          ln -s $PWD $(go env GOPATH)/src/github.com/ipfs-shipyard/gomobile-ipfs
-        shell: bash
+      # - name: Install Go mod
+      #   if: steps.cache.outputs.cache-hit != 'true'
+      #   working-directory: go
+      #   run: GO111MODULE=on go mod vendor
 
-      - name: Restore Go mod cache
-        id: cache
-        uses: actions/cache@v1
-        with:
-          path: ~/go/pkg/mod
-          key: ${{ runner.os }}-go-${{ hashFiles('go/go.sum') }}
+      # - name: Install Java
+      #   uses: actions/setup-java@v1
+      #   with:
+      #     java-version: 1.8
 
-      - name: Install Go mod
-        if: steps.cache.outputs.cache-hit != 'true'
-        working-directory: go
-        run: GO111MODULE=on go mod vendor
+      # - name: Set TARGET_SDK in env
+      #   run: |
+      #     pip3 install -r packages/utils/yaml_get/requirements.txt
+      #     export GET_BIN=packages/utils/yaml_get/yaml_get.py
+      #     export GET_KEY=global.android.target_sdk_version
+      #     echo "##[set-env name=TARGET_SDK;]$($GET_BIN $GET_KEY)"
 
-      - name: Install Java
-        uses: actions/setup-java@v1
-        with:
-          java-version: 1.8
+      # - name: Install Android SDK
+      #   run:
+      #     SDK_MAN=$HOME/Library/Android/sdk/tools/bin/sdkmanager;
+      #     BTOOLS=$($SDK_MAN --list | grep "build-tools;$TARGET_SDK");
+      #     BTOOL=$(echo $BTOOLS | tail -n1 | cut -d'|' -f1 | tr -d ' ');
+      #     PLATFORMS=$($SDK_MAN --list | grep "platforms;android-$TARGET_SDK");
+      #     PLATFORM=$(echo $PLATFORMS | tail -n1 | cut -d'|' -f1 | tr -d ' ');
 
-      - name: Set TARGET_SDK in env
-        run: |
-          pip3 install -r packages/utils/yaml_get/requirements.txt
-          export GET_BIN=packages/utils/yaml_get/yaml_get.py
-          export GET_KEY=global.android.target_sdk_version
-          echo "##[set-env name=TARGET_SDK;]$($GET_BIN $GET_KEY)"
+      #     $SDK_MAN --install "$BTOOL" platform-tools "$PLATFORM" ndk-bundle
+      #     > /dev/null
 
-      - name: Install Android SDK
-        run:
-          SDK_MAN=$HOME/Library/Android/sdk/tools/bin/sdkmanager;
-          BTOOLS=$($SDK_MAN --list | grep "build-tools;$TARGET_SDK");
-          BTOOL=$(echo $BTOOLS | tail -n1 | cut -d'|' -f1 | tr -d ' ');
-          PLATFORMS=$($SDK_MAN --list | grep "platforms;android-$TARGET_SDK");
-          PLATFORM=$(echo $PLATFORMS | tail -n1 | cut -d'|' -f1 | tr -d ' ');
+      # - name: Build Core
+      #   working-directory: packages
+      #   run: make build_core
 
-          $SDK_MAN --install "$BTOOL" platform-tools "$PLATFORM" ndk-bundle
-          > /dev/null
+      # - name: Generate docs
+      #   run: |
+      #     gem install jazzy
+      #     rm -rf docs
+      #     cd packages && make docgen
 
-      - name: Build Core
-        working-directory: packages
-        run: make build_core
+      # - name: Retrieve changelog from Github PR body
+      #   run:
+      #     brew install jq;
+      #     cat ${{ github.event_path }} | jq -r .pull_request.body > /tmp/body;
+      #     cat /tmp/body | sed -ne '/^## Changelog/,$ p' > /tmp/changelog;
 
-      - name: Generate docs
-        run: |
-          gem install jazzy
-          rm -rf docs
-          cd packages && make docgen
+      #     if [[ -z $(cat /tmp/changelog) ]]; then
+      #         echo "[Error] empty changelog"; exit 1;
+      #     fi
 
-      - name: Retrieve changelog from Github PR body
-        run:
-          brew install jq;
-          cat ${{ github.event_path }} | jq -r .pull_request.body > /tmp/body;
-          cat /tmp/body | sed -ne '/^## Changelog/,$ p' > /tmp/changelog;
+      #     cat /tmp/changelog | sed '/<!--/,/-->/d' > /tmp/changelog_nc;
 
-          if [[ -z $(cat /tmp/changelog) ]]; then
-              echo "[Error] empty changelog"; exit 1;
-          fi
+      # - name: Generate changelog
+      #   run:
+      #     cat /tmp/changelog_nc >> packages/release_notes/changelog
 
-          cat /tmp/changelog | sed '/<!--/,/-->/d' > /tmp/changelog_nc;
+      # - name: Push docs and changelog
+      #   uses: github-actions-x/commit@v2.3
+      #   with:
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #     push-branch: master
+      #     commit-message: 'docs: generate docs and changelog'
+      #     files: docs packages/release_notes/changelog
 
-      - name: Generate changelog
-        run:
-          cat /tmp/changelog_nc >> packages/release_notes/changelog
+  # publish:
+    # name: Publish Bridge and Core
+    # runs-on: macos-latest
+    # timeout-minutes: 30
+    # steps:
+      # - name: Checkout changes
+      #   uses: actions/checkout@v2
 
-      - name: Push docs and changelog
-        uses: github-actions-x/commit@v2.3
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          push-branch: master
-          commit-message: 'docs: generate docs and changelog'
-          files: docs packages/release_notes/changelog
+      # - name: Install Go
+      #   uses: actions/setup-go@v1
+      #   with:
+      #     go-version: 1.14
 
-  publish:
-    name: Publish Bridge and Core
-    runs-on: macos-latest
-    timeout-minutes: 30
-    steps:
-      - name: Checkout changes
-        uses: actions/checkout@v2
+      # - name: Set GOPATH in env
+      #   run: |
+      #     echo "##[set-env name=GOPATH;]$(go env GOPATH)"
+      #     echo "##[add-path]$(go env GOPATH)/bin"
+      #     mkdir -p $(go env GOPATH)/src/github.com/ipfs-shipyard
+      #     ln -s $PWD $(go env GOPATH)/src/github.com/ipfs-shipyard/gomobile-ipfs
+      #   shell: bash
 
-      - name: Install Go
-        uses: actions/setup-go@v1
-        with:
-          go-version: 1.14
+      # - name: Restore Go mod cache
+      #   id: cache
+      #   uses: actions/cache@v1
+      #   with:
+      #     path: ~/go/pkg/mod
+      #     key: ${{ runner.os }}-go-${{ hashFiles('go/go.sum') }}
 
-      - name: Set GOPATH in env
-        run: |
-          echo "##[set-env name=GOPATH;]$(go env GOPATH)"
-          echo "##[add-path]$(go env GOPATH)/bin"
-          mkdir -p $(go env GOPATH)/src/github.com/ipfs-shipyard
-          ln -s $PWD $(go env GOPATH)/src/github.com/ipfs-shipyard/gomobile-ipfs
-        shell: bash
+      # - name: Install Go mod
+      #   if: steps.cache.outputs.cache-hit != 'true'
+      #   working-directory: go
+      #   run: GO111MODULE=on go mod vendor
 
-      - name: Restore Go mod cache
-        id: cache
-        uses: actions/cache@v1
-        with:
-          path: ~/go/pkg/mod
-          key: ${{ runner.os }}-go-${{ hashFiles('go/go.sum') }}
+      # - name: Install Java
+      #   uses: actions/setup-java@v1
+      #   with:
+      #     java-version: 1.8
 
-      - name: Install Go mod
-        if: steps.cache.outputs.cache-hit != 'true'
-        working-directory: go
-        run: GO111MODULE=on go mod vendor
+      # - name: Set TARGET_SDK in env
+      #   run: |
+      #     pip3 install -r packages/utils/yaml_get/requirements.txt
+      #     export GET_BIN=packages/utils/yaml_get/yaml_get.py
+      #     export GET_KEY=global.android.target_sdk_version
+      #     echo "##[set-env name=TARGET_SDK;]$($GET_BIN $GET_KEY)"
 
-      - name: Install Java
-        uses: actions/setup-java@v1
-        with:
-          java-version: 1.8
+      # - name: Install Android SDK
+      #   run:
+      #     SDK_MAN=$HOME/Library/Android/sdk/tools/bin/sdkmanager;
+      #     BTOOLS=$($SDK_MAN --list | grep "build-tools;$TARGET_SDK");
+      #     BTOOL=$(echo $BTOOLS | tail -n1 | cut -d'|' -f1 | tr -d ' ');
+      #     PLATFORMS=$($SDK_MAN --list | grep "platforms;android-$TARGET_SDK");
+      #     PLATFORM=$(echo $PLATFORMS | tail -n1 | cut -d'|' -f1 | tr -d ' ');
 
-      - name: Set TARGET_SDK in env
-        run: |
-          pip3 install -r packages/utils/yaml_get/requirements.txt
-          export GET_BIN=packages/utils/yaml_get/yaml_get.py
-          export GET_KEY=global.android.target_sdk_version
-          echo "##[set-env name=TARGET_SDK;]$($GET_BIN $GET_KEY)"
+      #     $SDK_MAN --install "$BTOOL" platform-tools "$PLATFORM" ndk-bundle
+      #     > /dev/null
 
-      - name: Install Android SDK
-        run:
-          SDK_MAN=$HOME/Library/Android/sdk/tools/bin/sdkmanager;
-          BTOOLS=$($SDK_MAN --list | grep "build-tools;$TARGET_SDK");
-          BTOOL=$(echo $BTOOLS | tail -n1 | cut -d'|' -f1 | tr -d ' ');
-          PLATFORMS=$($SDK_MAN --list | grep "platforms;android-$TARGET_SDK");
-          PLATFORM=$(echo $PLATFORMS | tail -n1 | cut -d'|' -f1 | tr -d ' ');
+      # - name: Update Cocoapods
+      #   run: |
+      #     gem install cocoapods
+      #     pod setup
 
-          $SDK_MAN --install "$BTOOL" platform-tools "$PLATFORM" ndk-bundle
-          > /dev/null
+      # - name: Generate Semantic Release version
+      #   uses: cycjimmy/semantic-release-action@v2
+      #   id: semantic
+      #   with:
+      #     dry_run: true
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Update Cocoapods
-        run: |
-          gem install cocoapods
-          pod setup
-
-      - name: Generate Semantic Release version
-        uses: cycjimmy/semantic-release-action@v2
-        id: semantic
-        with:
-          dry_run: true
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Remove leading v from version
-        run:
-          echo "##[set-env name=VERSION;]$(echo $VVERSION | cut -dv -f2)"
-        env:
-          VVERSION: ${{ steps.semantic.outputs.new_release_version }}
-
-      - name: Publish Android/iOS Bridge and Core
-        working-directory: packages
-        env:
-          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
-          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
-          BINTRAY_GPG_PASS: ${{ secrets.BINTRAY_GPG_PASS }}
-          GOMOBILE_IPFS_VERSION: ${{ env.VERSION }}
-        run: |
-          make publish_core.android
-          make publish_bridge.android
-          make publish_core.ios
-          make publish_bridge.ios
+      # - name: Publish Android/iOS Bridge and Core
+      #   working-directory: packages
+      #   env:
+      #     BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
+      #     BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
+      #     BINTRAY_GPG_PASS: ${{ secrets.BINTRAY_GPG_PASS }}
+      #     GOMOBILE_IPFS_VERSION: ${{ env.VERSION }}
+      #   run: |
+      #     make publish_core.android
+      #     make publish_bridge.android
+      #     make publish_core.ios
+      #     make publish_bridge.ios
